// AUTH ACTION
export const AUTH = "AUTH";

// LOG-OUT ACTION
export const LOGOUT = "LOGOUT";

// CREATE_STRIPE_ACCOUNT ACTION
export const CREATE_STRIPE_ACCOUNT = "CREATE_STRIPE_ACCOUNT";

// CREATE ACTION
export const CREATE = "CREATE";

// UPDATE ACTION
export const UPDATE = "UPDATE";

// DELETE ACTION
export const DELETE = "DELETE";

// FETCH ALL ACTION
export const FETCH_ALL = "FETCH_ALL";

// LIKE ACTION
export const LIKE = "LIKE";