export const SET_SERVICES = "SET_SERVICES";
export const TOGGLE_SERVICE_FETCHING_STATE = "TOGGLE_SERVICE_FETCHING_STATE";
export const SET_CURRENT_SERVICE = "SET_CURRENT_SERVICE"
export const TOGGLE_CURRENT_SERVICE_FETCHING_STATE ="TOGGLE_CURRENT_SERVICE_FETCHING_STATE";

export const SET_PRODUCTS = "SET_PRODUCTS";
export const TOGGLE_PRODUCT_FETCHING_STATE = "TOGGLE_PRODUCT_FETCHING_STATE";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT"
export const TOGGLE_CURRENT_PRODUCT_FETCHING_STATE ="TOGGLE_CURRENT_PRODUCT_FETCHING_STATE";